"""Protocols separating playback orchestration from concrete backends."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from .models import PlaybackEntry, PlaybackSnapshot, ResolvedSource, SourceReference


@runtime_checkable
class SourceResolver(Protocol):
    async def resolve(self, reference: SourceReference) -> ResolvedSource: ...

    async def close(self) -> None: ...


@runtime_checkable
class PlaybackEventSink(Protocol):
    async def track_started(self, guild_id: int, entry: PlaybackEntry) -> None: ...

    async def track_failed(self, guild_id: int, entry: PlaybackEntry, reason: str) -> None: ...

    async def queue_ended(self, guild_id: int, previous: PlaybackEntry | None) -> None: ...


@runtime_checkable
class PlaybackSession(Protocol):
    @property
    def guild_id(self) -> int: ...

    def snapshot(self) -> PlaybackSnapshot: ...

    async def enqueue(self, entry: PlaybackEntry, *, start_if_idle: bool = True) -> bool: ...

    async def skip(self) -> bool: ...

    async def set_paused(self, paused: bool) -> bool: ...

    async def stop(self, *, clear_queue: bool = True) -> None: ...

    async def close(self) -> None: ...


@runtime_checkable
class PlaybackBackend(Protocol):
    async def get(self, guild_id: int) -> PlaybackSession | None: ...

    async def connect(self, guild: Any, channel: Any) -> PlaybackSession: ...

    async def close_guild(self, guild_id: int) -> None: ...

    async def close(self) -> None: ...
